import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar, NavbarActions, NavbarItem, NavbarLogo, NavbarMenu } from "@/Components/Navbar/layout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PHARMORIS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased`}
      >
         <Navbar>
        <NavbarLogo />
        <NavbarMenu>
          <NavbarItem label="Dashboard" />
          <NavbarItem label="Insights" />
        </NavbarMenu>
        <NavbarActions />
      </Navbar>
        {children}
      </body>
    </html>
  );
}
